# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM-Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
	pod 'SnapKit', '~> 5.0.0'
	pod 'RxSwift', '6.2.0'
	pod 'RxCocoa', '6.2.0'

  # Pods for MVVM-Practice

end
